---
title: Grammar
author: Karl Meakin
geometry: margin=1cm
output:
  pdf_document:
    highlight: pygments
    latex_engine: xelatex
    pandoc_args: "--pdf-engine-opt=--shell-escape"
header-includes:
    - \usepackage{syntax}
---

\renewcommand{\lit}[1]{\texttt{#1}}
\newcommand{\opt}[1]{#1\textsuperscript{?}}
\newcommand{\manyZero}[1]{#1\textsuperscript{*}}
\newcommand{\manyOne}[1]{#1\textsuperscript{+}}

\newcommand{\manyZeroComma}[1]{#1\textsuperscript{,*}}
\newcommand{\manyOneComma}[1]{#1\textsuperscript{,+}}

\newcommand{\lcurly}{\lit{\{}}
\newcommand{\rcurly}{\lit{\}}}

# Comments
\begin{grammar}
<LineComment> ::= \lit{//} \manyZero{<any character>} <newline or end of file>

<BlockComment> ::= \lit{/*} \manyZero{<any character>} \manyZero{<BlockComment>} <any character> \lit{*/}
\end{grammar}

# Definitions
\begin{grammar}
<SourceFile> ::= <Definition>

<Definition> ::= <FnDefinition> | <StructDefinition> | <EnumDefinition> 

<FnDefinition> ::= \lit{fn} <ParamList> <ReturnType> <BlockExpr>

<StructDefinition> ::= \lit{struct} <Ident> \lcurly \manyZero{<Field>} \rcurly

<EnumDefinition> ::= \lit{enum} <Ident> \lcurly \manyZero{<EnumVariant>} \rcurly

<EnumVariant> ::= <Ident> \lcurly \manyZero{<Field>} \rcurly

<Field> ::= <Ident> \lit{:} <Type>
\end{grammar}

# Identifiers
\begin{grammar}
<Ident> ::= (<IdentStart>) \manyZero{<IdentContinue>}

<IdentStart> ::= <any character in the Unicode XID_Start character class> | \lit{_}

<IdentContinue> ::= <any character in the Unicode XID_Continue character class>
\end{grammar}

(FOOTNOTE: https://www.unicode.org/reports/tr31/#Table_Lexical_Classes_for_Identifiers)

# Literals
\begin{grammar}
<Lit> ::= <BoolLit> | <IntLit> | <FloatLit> | <CharLit>

<BoolLit> ::= \lit{true} | \lit{false} 

<IntLit> ::= <BinInt> | <DecInt> | <HexInt>

<BinInt> ::= \lit{0b} | \lit{0B}) <BinDigit> \manyZero{<BinDigit_>}

<BinDigit> ::= \lit{0} | \lit{1}

<BinDigit_> ::= <BinDigit> | \lit{_}

<DecInt> ::= <DecDigit> \manyZero{<DecDigit_>}

<DecDigit> ::= \lit{0} | \lit{1} | \lit{2} | \lit{3} | \lit{4} | \lit{5} | \lit{6} | \lit{7} | \lit{8} | \lit{9}

<DecDigit_> ::= <DecDigit> | \lit{_}

<HexInt> ::= (\lit{0x} | \lit{0X}) <HexDigit> \manyZero{<HexDigit_>}

<HexDigit_> ::= <HexDigit> | \lit{_}

<CharLit> ::= <SimpleChar> | <EscapedChar> | <UnicodeChar>

<SimpleChar> ::= \lit{'} <any character except single quote> \lit{'}

<EscapedChar> ::= \verb$'\n'$ | \verb$'\t'$ | \verb$'\\'$ | \verb$'\0'$ | \verb$'\''$ | \verb$'\"'$

<UnicodeChar> ::= \lit{'} (\verb$\u$ | \verb$\U$) <HexDigit> \manyZero{<HexDigit_>} \lit{'}
\end{grammar}

# Expressions
\begin{grammar}
<Expr> ::= <LitExpr> 
\alt <ParenExpr> 
\alt <VarExpr> 
\alt <UnopExpr> 
\alt <BinopExpr> 
\alt <CallExpr> 
\alt <LambdaExpr> 
\alt <IfExpr> 
\alt <LoopExpr> 
\alt <BreakExpr>
\alt <ContinueExpr>
\alt <ReturnExpr>
\alt <TupleExpr>
\alt <StructExpr>
\alt <EnumExpr>
\alt <FieldExpr>
\alt <MatchExpr>
\alt <BlockExpr> 

<LitExpr> ::= <Lit>

<ParenExpr> ::= \lit{(} <Expr> \lit{)}

<VarExpr> ::= <Ident>

<UnopExpr> ::= <Unop> <Expr>

<Unop> ::= \lit{+} | \lit{-}

<BinopExpr> ::= <Expr> <Binop> <Expr>

<Binop> ::= \lit{+} | \lit{-} | \lit{*} | \lit{/} | \lit{=} | \lit{==} | \lit{!=}  | \verb$<$ | \verb$>$ | \verb$<=$ | \verb$>=$ | \verb$||$ | \verb$&&$

<CallExpr> ::= <Expr> \lit{(} \manyZeroComma{<Expr>} \lit{)}

<LambdaExpr> ::= \lit{(} \manyZeroComma{<Pat>} \lit{)} \lit{=>} <Expr>

<IfExpr> ::= \lit{if} <Expr> <BlockExpr> \manyZero{(\lit{else}  <Expr> <BlockExpr>)} \opt{(\lit{else} <BlockExpr>)}

<LoopExpr> ::= \lit{loop} <Expr> <BlockExpr>

<BreakExpr> ::= \lit{break} \opt{<Expr>}

<ContinueExpr> ::= \lit{continue}

<ReturnExpr> ::= \lit{return} \opt{<Expr>}

<TupleExpr> ::= \lit{(} <Expr> \lit{,} \lit{)} | \lit{(} \manyZeroComma{<Expr>} \lit{)}

<StructExpr> ::= <Ident> \lcurly \manyZeroComma{(<Ident> \lit{:} <Expr>)} \rcurly

<EnumExpr> ::= <Ident> \lit{::} <Ident> \lcurly \manyZeroComma{(<Ident> \lit{:} <Expr>)} \rcurly

<FieldExpr> ::= <Expr> \lit{.} (<Ident> | <IntLit>)

<MatchExpr> ::= \lit{match} <Expr> \lcurly \manyZeroComma{<MatchCase>} \rcurly

<MatchCase> ::= <Pat> \lit{=>} <Expr>
\end{grammar}

## Expression precedence
| Expression/Operator    | Associativity
|------------------------|-----------
| VarExpr (strongest)    |
| FieldExpr              | left
| CallExpr               | 
| UnaryExpr              |
| \lit{*}, \lit{/}       | left
| \lit{+}, \lit{-}       | left
| \lit{==}, \lit{!=}, \lit{<}, \lit{>}, \lit{<=}, \lit{>=} | left 
| \verb$&&$              | left
| \lit{||}               | left
| \lit{=}                | right
| LambdaExpr (weakest)   | right


# Types
\begin{grammar}
<Type> ::= <VarType> 
\alt <InferType>
\alt <TupleType>
\alt <FnType>

<VarType> ::= <Ident>

<InferType> ::= \lit{_}

<TupleType> ::= \lit{(} <Type> \lit{,} \lit{)} | \lit{(} \manyZeroComma{<Type>} \lit{)}

<FnType> ::= \lit{(} <Type>\textsuperscript{,*} \lit{)} \lit{->} <Type>
\end{grammar}


## Type precedence
| Operator           | Associativity
|--------------------|--------------
| FnType (\lit{->})  | Right


# Patterns
\begin{grammar}
<Pat> ::= <LitPat> 
\alt <VarPat>
\alt <IgnorePat>
\alt <TuplePat>
\alt <StructPat>
\alt <EnumPat>

<LitPat> ::= <Lit>

<VarPat> ::= <Ident>

<IgnorePat> ::= \lit{_}

<TuplePat> ::= \lit{(} <Pat> \lit{,} \lit{)} | \lit{(} \manyZeroComma{<Pat>} \lit{)}

<StructPat> ::= <Ident> \lcurly <FieldPat>\textsuperscript{,*} \rcurly

<EnumExpr> ::= <Ident> \lit{::} <Ident> \lcurly \manyZeroComma{<FieldPat>} \rcurly
\end{grammar}


